name: Build ZMK firmware
on:
  push:
    branches:
      - "zmk-for-corne"
    paths:
      - "config/**"
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
